In [1]:
import pandas as pd

In [4]:
df = pd.read_csv(r'D:\Portfolio\DS\Home Credit\Credit_home-analyst\data\raw\dazone_sample_test.csv')

In [5]:
df.head()

,Unnamed: 0,customer_id,treatment,cash_sign_30d,card_sign_30d,min_sign_vol,avg_sign_vol,cnt_month_from_last_appl,cli_age,cli_job,...,max_cntr_len_fi_12m,amt_terminated_loan_12m,cnt_terminated_loan_12m,cnt_month_over3_credit_card_6m,cnt_noinsurance_loan_24m,cnt_earlyterminated_cash,cnt_earlyterminted_pos,cnt_inbound_tls_12m,cnt_month_from_first_transaction,cnt_month_from_last_transaction
0,0,35,cash,NaN,NaN,6061000.0,6143000.0,52,30,OTHER,...,NaN,NaN,NaN,NaN,0.0,0,0,NaN,NaN,NaN
1,1,68,cash,NaN,NaN,3309000.0,3405000.0,83,36,OTHER,...,NaN,NaN,NaN,NaN,0.0,0,0,NaN,NaN,NaN
2,2,84,card,NaN,NaN,3108000.0,3066000.0,102,40,OTHER,...,NaN,NaN,NaN,NaN,0.0,0,0,NaN,NaN,NaN
3,3,122,cash,NaN,NaN,26374000.0,26146000.0,34,23,WORKER,...,NaN,0.0,0.0,0.0,0.0,0,0,0.0,NaN,NaN
4,4,190,card,NaN,NaN,4036000.0,3837000.0,101,25,OTHER,...,NaN,NaN,NaN,NaN,0.0,0,0,NaN,NaN,NaN

In [ ]:
df1 = pd.read_csv(r'D:\Portfolio\DS\Home Credit\Credit_home-analyst\data\raw\dazone_sample.csv')

In [7]:
df1.head()

,Unnamed: 0,customer_id,treatment,cash_sign_30d,card_sign_30d,min_sign_vol,avg_sign_vol,cnt_month_from_last_appl,cli_age,cli_job,...,max_cntr_len_fi_12m,amt_terminated_loan_12m,cnt_terminated_loan_12m,cnt_month_over3_credit_card_6m,cnt_noinsurance_loan_24m,cnt_earlyterminated_cash,cnt_earlyterminted_pos,cnt_inbound_tls_12m,cnt_month_from_first_transaction,cnt_month_from_last_transaction
0,0,11,cash,0,0,4141000.0,3986000.0,141,25,ENGINEER,...,NaN,NaN,NaN,NaN,0.0,0,0,NaN,NaN,NaN
1,1,19,card,0,0,2290000.0,3140000.0,12,37,WORKER,...,183.0,2312000.0,1.0,0.0,0.0,0,0,0.0,NaN,NaN
2,2,48,card,0,0,1604000.0,2943000.0,6,34,FARMER,...,NaN,0.0,0.0,0.0,0.0,0,0,NaN,NaN,NaN
3,3,59,card,0,0,5090000.0,7839000.0,9,29,FARMER,...,245.0,0.0,0.0,0.0,0.0,0,0,0.0,9.0,9.0
4,4,60,cash,0,0,7617000.0,9165000.0,71,30,SERVICES,...,NaN,0.0,0.0,0.0,0.0,0,0,NaN,NaN,NaN

In [10]:
df.shape

(34080, 45)

In [11]:
df1.shape

(136992, 45)

In [12]:
merged_df = df.merge(df1, on='customer_id', how='inner')
merged_df.head()

Empty DataFrame
Columns: [Unnamed: 0_x, customer_id, treatment_x, cash_sign_30d_x, card_sign_30d_x, min_sign_vol_x, avg_sign_vol_x, cnt_month_from_last_appl_x, cli_age_x, cli_job_x, cli_marital_status_x, cli_contact_region_level_x, cli_education_x, cli_emp_period_x, last_offer_limit_x, last_process_channel_x, f_approve_last_process_x, cnt_connected_tls_x, cnt_fail_tls_3m_x, f_appointment_3m_x, cnt_total_payment_x, risk_grp_x, cli_contact_region_population_grp_x, ratio_monthly_amt_l6m_vs_n6m_x, worst_credit_status_x, cnt_month_status1_x, ratio_vol_hcvn_cash_appl_12m_x, f_ever_default_x, ratio_conn_tls_weekend_12m_x, ratio_conn_tls_endmonth_12m_x, cnt_bank_inst_appl_12m_x, cnt_fi_inst_appl_12m_x, cnt_report_bank_6m_x, cnt_report_institution_12m_x, cnt_lender_has2pay_last_24m_x, max_cntr_len_fi_12m_x, amt_terminated_loan_12m_x, cnt_terminated_loan_12m_x, cnt_month_over3_credit_card_6m_x, cnt_noinsurance_loan_24m_x, cnt_earlyterminated_cash_x, cnt_earlyterminted_pos_x, cnt_inbound_tls_12m_x, cnt_month_from_first_transaction_x, cnt_month_from_last_transaction_x, Unnamed: 0_y, treatment_y, cash_sign_30d_y, card_sign_30d_y, min_sign_vol_y, avg_sign_vol_y, cnt_month_from_last_appl_y, cli_age_y, cli_job_y, cli_marital_status_y, cli_contact_region_level_y, cli_education_y, cli_emp_period_y, last_offer_limit_y, last_process_channel_y, f_approve_last_process_y, cnt_connected_tls_y, cnt_fail_tls_3m_y, f_appointment_3m_y, cnt_total_payment_y, risk_grp_y, cli_contact_region_population_grp_y, ratio_monthly_amt_l6m_vs_n6m_y, worst_credit_status_y, cnt_month_status1_y, ratio_vol_hcvn_cash_appl_12m_y, f_ever_default_y, ratio_conn_tls_weekend_12m_y, ratio_conn_tls_endmonth_12m_y, cnt_bank_inst_appl_12m_y, cnt_fi_inst_appl_12m_y, cnt_report_bank_6m_y, cnt_report_institution_12m_y, cnt_lender_has2pay_last_24m_y, max_cntr_len_fi_12m_y, amt_terminated_loan_12m_y, cnt_terminated_loan_12m_y, cnt_month_over3_credit_card_6m_y, cnt_noinsurance_loan_24m_y, cnt_earlyterminated_cash_y, cnt_earlyterminted_pos_y, cnt_inbound_tls_12m_y, cnt_month_from_first_transaction_y, cnt_month_from_last_transaction_y]
Index: []

[0 rows x 89 columns]

In [ ]:
union_df = pd.concat([df, df1], ignore_index=True).drop_duplicates().reset_index(drop=True)
sorted_union_df = union_df.sort_values(by='customer_id').reset_index(drop=True)
sorted_union_df.head()

,Unnamed: 0,customer_id,treatment,cash_sign_30d,card_sign_30d,min_sign_vol,avg_sign_vol,cnt_month_from_last_appl,cli_age,cli_job,...,max_cntr_len_fi_12m,amt_terminated_loan_12m,cnt_terminated_loan_12m,cnt_month_over3_credit_card_6m,cnt_noinsurance_loan_24m,cnt_earlyterminated_cash,cnt_earlyterminted_pos,cnt_inbound_tls_12m,cnt_month_from_first_transaction,cnt_month_from_last_transaction
0,0,35,cash,NaN,NaN,6061000.0,6143000.0,52,30,OTHER,...,NaN,NaN,NaN,NaN,0.0,0,0,NaN,NaN,NaN
1,1,68,cash,NaN,NaN,3309000.0,3405000.0,83,36,OTHER,...,NaN,NaN,NaN,NaN,0.0,0,0,NaN,NaN,NaN
2,2,84,card,NaN,NaN,3108000.0,3066000.0,102,40,OTHER,...,NaN,NaN,NaN,NaN,0.0,0,0,NaN,NaN,NaN
3,3,122,cash,NaN,NaN,26374000.0,26146000.0,34,23,WORKER,...,NaN,0.0,0.0,0.0,0.0,0,0,0.0,NaN,NaN
4,4,190,card,NaN,NaN,4036000.0,3837000.0,101,25,OTHER,...,NaN,NaN,NaN,NaN,0.0,0,0,NaN,NaN,NaN